### ISSUE TITLE
Build example Data Studio template for PPF adopters

### ISSUE THREAD

**Issue by mediajunkie** [cagov/analytics-feedback-loops#11]

**Comment by britt-allen** [comment]
WIP template here: https://datastudio.google.com/reporting/cc37d2e9-9e1c-47f9-9a1b-34e2c1b66a15

Need to add some docs to it.

cc for visibility: @mediajunkie @thepegisin @jpetrucione

**Comment by mediajunkie** [comment]
thank you!

**Comment by mediajunkie** [comment]
@britt-allen would love to connect and discuss the use of this, what else we need to prepare, etc.

**Comment by mediajunkie** [comment]
I think this task is done!
