### ISSUE TITLE
Fix search bugs

### ISSUE THREAD

**Issue by mediajunkie** [cagov/analytics-feedback-loops#7]
Search results issues (will need steps to reproduce):
- [x] duplicate comments in results
- [ ] search didn’t actually capture everything ("I could search for an exact word or phrase I had already seen in comments and it would say there was no data")
- [ ] After searching once, a subsequent search on a new term comes up blank (despite reporting a nonzero number of results) until refreshing the page

**Comment by britt-allen** [comment]
Fixed the duplicate problem with @aaronhans and Syntasa, the second and third bullet seems to be a less than fab feature of data studio and nothing we can control, but something the new internal looker dashboard should be able to.

closing! :)
