### ISSUE TITLE
Sort on any field

### ISSUE THREAD

**Issue by mediajunkie** [cagov/analytics-feedback-loops#8]

**Comment by britt-allen** [comment]
shows how to sort on any field in the existing dashbaord, this is not (or no longer) a data studio limitation.

https://user-images.githubusercontent.com/47340362/147008241-5f81f4c7-dd8d-41fa-9c9b-4f930ca71bad.mov
 
cc: @thepegisin @m-sullivan7 @LizNobriga @mediajunkie @clarita1980
